In [8]:
%pip install -e .

/Users/roger.caminal/working_area/hamcontestlog/.venv/bin/python3: No module named pip
Note: you may need to restart the kernel to use updated packages.

# Imports and setup

In [1]:
import os
import duckdb

In [2]:
%rm hamcontestlog.db

In [3]:
os.environ["HAMCONTESTLOG_DB"] = "hamcontestlog.db"

In [12]:
con.close()

# Add contest

- Add the contest definition from the YAML file `cqww/2025cqwwcw.yaml`. 
- Updates the table contests

In [13]:
%%bash
hamcontestlog contest add cqww/2025cqwwcw.yaml

Default contest 2025cqwwcw loaded.

In [15]:
con = duckdb.connect("hamcontestlog.db")
_df = con.execute("select * from contests limit 10").fetchdf()
con.close()

_df

,contest_id,name,sponsor,mode,start_time,end_time,bands,metadata
0,2025cqwwcw,CQ World Wide DX Contest CW 2025,CQ,CW,2025-11-29,2025-11-30 23:59:59,"160m,80m,40m,20m,15m,10m","{""log_source"": ""cqww""}"

# Ingest logs

- Download and ingest one public Cabrillo log.
- Updates the tables `logs` and `qsos`.

In [17]:
%%bash
hamcontestlog ingest log --contest 2025cqwwcw --call EF6T --source cqww
hamcontestlog ingest log --contest 2025cqwwcw --call CR6K --source cqww

Ingested log for EF6T from cqww.
Ingested log for CR6K from cqww.

In [18]:
con = duckdb.connect("hamcontestlog.db")
_df = con.execute("select * from logs").fetchdf()
con.close()

_df

,log_id,contest_id,callsign,operator,club,category,claimed_score,raw_metadata
0,1,2025cqwwcw,EF6T,None,CATALONIA CONTEST CLUB,SINGLE-OP NON-ASSISTED ALL HIGH CW ONE FIXED,12254858,"{""START-OF-LOG"":""3.0"",""CONTEST"":""CQ-WW-CW"",""CA..."
1,2,2025cqwwcw,EF6T,None,CATALONIA CONTEST CLUB,SINGLE-OP NON-ASSISTED ALL HIGH CW ONE FIXED,12254858,"{""START-OF-LOG"":""3.0"",""CONTEST"":""CQ-WW-CW"",""CA..."
2,3,2025cqwwcw,CR6K,None,EA CONTEST CLUB,SINGLE-OP NON-ASSISTED ALL HIGH CW ONE FIXED,14880550,"{""START-OF-LOG"":""3.0"",""CONTEST"":""CQ-WW-CW"",""CA..."

In [24]:
con = duckdb.connect("hamcontestlog.db")
_df = con.execute(
    """
select * 
from qsos 
where 1=1
and my_call = 'EF6T'
    """).fetchdf()
con.close()

_df

,qso_id,log_id,qso_time,band,mode,freq_hz,my_call,their_call,rst_sent,rst_rcvd,exch_sent,exch_rcvd,mult_flags
0,1,1,2025-11-29 00:00:00,40m,CW,7045000.0,EF6T,UA7K,599,599,14,16,None
1,2,1,2025-11-29 00:00:00,40m,CW,7045000.0,EF6T,KA8JBK,599,599,14,04,None
2,3,1,2025-11-29 00:00:00,40m,CW,7045000.0,EF6T,HA6Y,599,599,14,15,None
3,4,1,2025-11-29 00:01:00,40m,CW,7045000.0,EF6T,DM5GG,599,599,14,14,None
4,5,1,2025-11-29 00:01:00,40m,CW,7045000.0,EF6T,K1ZJA,599,599,14,05,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19613,19614,2,2025-11-30 23:57:00,80m,CW,3549000.0,EF6T,W1CSM,599,599,14,05,None
19614,19615,2,2025-11-30 23:58:00,80m,CW,3549000.0,EF6T,DL3EL,599,599,14,14,None
19615,19616,2,2025-11-30 23:58:00,40m,CW,7041000.0,EF6T,DL6NCY,599,599,14,14,None
19616,19617,2,2025-11-30 23:59:00,80m,CW,3549000.0,EF6T,HG6C,599,599,14,15,None
19617,19618,2,2025-11-30 23:59:00,40m,CW,7041000.0,EF6T,KM4AF,599,599,14,05,None

In [18]:
%%bash 

hamcontestlog contest add cqww/2025cqwwcw.yaml

# hamcontestlog ingest log --contest 2024cqwwcw --call EF6T --source cqww
# # hamcontestlog ingest logs --contest 2024cqwwcw

# hamcontestlog enrich calls --contest 2024cqwwcw

# hamcontestlog enrich qsos --contest 2024cqwwcw

# hamcontestlog score cqww --contest 2024cqwwcw --call EF6T
# # hamcontestlog score cqww --contest 2024cqwwcw --all

Default contest 2024cqwwcw loaded.

# Dummy analysis

In [ ]:
try

In [25]:
import duckdb
con = duckdb.connect("hamcontestlog.db")

In [26]:
con.execute("SHOW TABLES").fetchdf()

              name
0  call_enrichment
1         contests
2             logs
3      qso_scoring
4             qsos
5        rbn_spots

In [34]:
con.execute("select * from contests limit 10").fetchdf()

,contest_id,name,sponsor,mode,start_time,end_time,bands,metadata
0,2024cqwwcw,CQ World Wide DX Contest CW 2024,CQ,CW,2024-11-23,2024-11-24 23:59:59,"160m,80m,40m,20m,15m,10m","{""log_source"": ""cqww""}"

In [35]:
con.execute("select * from logs limit 10").fetchdf()

,log_id,contest_id,callsign,operator,club,category,claimed_score,raw_metadata
0,1,2024cqwwcw,EF6T,None,CATALONIA CONTEST CLUB,SINGLE-OP NON-ASSISTED ALL HIGH CW ONE FIXED,12486666,"{""START-OF-LOG"":""3.0"",""CONTEST"":""CQ-WW-CW"",""CA..."

In [36]:
con.execute("select * from qsos limit 10").fetchdf()

,qso_id,log_id,qso_time,band,mode,freq_hz,my_call,their_call,rst_sent,rst_rcvd,exch_sent,exch_rcvd,mult_flags
0,1,1,2024-11-23 00:00:00,40m,CW,7044000.0,EF6T,YR8D,599,599,14,20,None
1,2,1,2024-11-23 00:00:00,40m,CW,7044000.0,EF6T,N1IX,599,599,14,05,None
2,3,1,2024-11-23 00:01:00,20m,CW,14041000.0,EF6T,W0EAR,599,599,14,04,None
3,4,1,2024-11-23 00:01:00,20m,CW,14041000.0,EF6T,NC3Y,599,599,14,05,None
4,5,1,2024-11-23 00:01:00,20m,CW,14041000.0,EF6T,KB4DX,599,599,14,05,None
5,6,1,2024-11-23 00:02:00,40m,CW,7044000.0,EF6T,PC5Q,599,599,14,14,None
6,7,1,2024-11-23 00:02:00,20m,CW,14041000.0,EF6T,K1AR,599,599,14,05,None
7,8,1,2024-11-23 00:03:00,20m,CW,14041000.0,EF6T,AB9YC,599,599,14,04,None
8,9,1,2024-11-23 00:03:00,40m,CW,7044000.0,EF6T,VE3NNT,599,599,14,04,None
9,10,1,2024-11-23 00:03:00,20m,CW,14041000.0,EF6T,K3TS,599,599,14,05,None

In [37]:
con.execute("select * from call_enrichment limit 10").fetchdf()

  callsign             dxcc  cq_zone  itu_zone continent prefix state province
0    KB4CG    United States        5         8        NA   None  None     None
1    M0XUU          England       14        27        EU   None  None     None
2     N2UU    United States        5         8        NA   None  None     None
3     K8CN    United States        5         8        NA   None  None     None
4   WB8BZK    United States        4         8        NA   None  None     None
5     N1JP    United States        5         8        NA   None  None     None
6     W3LL    United States        5         8        NA   None  None     None
7     ED1R            Spain       14        37        EU   None  None     None
8     NG2P    United States        5         8        NA   None  None     None
9     R5AK  European Russia       16        29        EU   None  None     None

In [23]:
con.execute("select * from qso_scoring limit 10").fetchdf()

,qso_id,contest_id,dxcc,cq_zone,itu_zone,prefix,state,province,hq,points,is_mult_dxcc,is_mult_cq_zone,is_mult_itu,is_mult_prefix,is_mult_state,is_mult_hq
0,9067,2024cqwwcw,United States,5,8,None,None,None,None,3,False,False,False,False,False,False
1,8797,2024cqwwcw,England,14,27,None,None,None,None,1,False,False,False,False,False,False
2,4862,2024cqwwcw,United States,5,8,None,None,None,None,3,False,False,False,False,False,False
3,7952,2024cqwwcw,United States,5,8,None,None,None,None,3,False,False,False,False,False,False
4,9010,2024cqwwcw,United States,4,8,None,None,None,None,3,False,False,False,False,False,False
5,9942,2024cqwwcw,United States,5,8,None,None,None,None,3,False,False,False,False,False,False
6,7850,2024cqwwcw,United States,5,8,None,None,None,None,3,False,False,False,False,False,False
7,2638,2024cqwwcw,Spain,14,37,None,None,None,None,1,False,False,False,False,False,False
8,8837,2024cqwwcw,United States,5,8,None,None,None,None,3,False,False,False,False,False,False
9,8695,2024cqwwcw,European Russia,16,29,None,None,None,None,1,False,False,False,False,False,False